apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-feed
  name: backend-feed
spec:
  replicas: 3
  selector:
    matchLabels:
      service: backend-feed
  template:
    metadata:
      labels:
        service: backend-feed
    spec:
      containers:
      - image: char2pie/udacity-restapi-feed
        name: backend-feed
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"                  
        env:
        - name: URL    # the reference name of the env. var
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: url   # the key in secret/env-config to get the value for URL
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: aws_bucket
        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: aws_profile
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: aws_region
        - name: POSTGRESS_DB
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: postgress_db
        - name: POSTGRESS_HOST
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: postgress_host
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: aws_secret_access_key
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: env-secret
              key: jwt_secret
        - name: POSTGRESS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: postgress_password
        - name: POSTGRESS_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: postgress_username      
      restartPolicy: Always
      